modLoader="javafml"
loaderVersion="[32,)"
license="MIT"

[[mods]]
modId="playerlister"
version="${file.jarVersion}"
displayName="Player Lister"
displayURL="https://www.curseforge.com/minecraft/mc-mods/player-lister"
credits=""
authors="Will BL"
description='''
Writes player list to a file every 15 seconds (configurable).
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,1.17)"
    ordering="NONE"
    side="BOTH"
